---
- name: Download restic withouth verified checksum file
  ansible.builtin.get_url:
    url: '{{ restic_url }}'
    dest: '{{ restic_download_path }}/restic.bz2'
    checksum: "sha256:{{ restic_url_checksums }}/SHA256SUMS"
    mode: "0644"
  register: get_url_restic
  when: restic_skip_checksum_verify

- name: Download restic with verified checksum file
  ansible.builtin.get_url:
    url: '{{ restic_url }}'
    dest: '{{ restic_download_path }}/restic.bz2'
    checksum: "sha256:{{ restic_checksums }}"
    mode: "0644"
  register: get_url_restic
  when: not restic_skip_checksum_verify

- name: Check download
  ansible.builtin.stat:
    path: '{{ restic_download_path }}/restic.bz2'
  register: file_status

- name: Install restic
  ansible.builtin.shell: |
    bzip2 -dc {{ restic_download_path }}/restic.bz2 > {{ restic_bin_bath }} &&
    rm -f {{ restic_download_path }}/restic.bz2
  register: restic_install_cmd
  changed_when: restic_install_cmd.rc == 0
  when: file_status.stat.exists

- name: Ensure permissions are correct
  ansible.builtin.file:
    path: '{{ restic_download_path }}/bin/restic-{{ restic_version }}'
    mode: '0755'
    owner: '{{ restic_dir_owner }}'
    group: '{{ restic_dir_group }}'
  when: not restic_non_root_setup | bool

- name: Ensure permissions are correct (non-root setup)
  ansible.builtin.file:
    path: '{{ restic_download_path }}/bin/restic-{{ restic_version }}'
    mode: '0750'
    owner: "{{ restic_non_root_setup_user }}"
    group: "{{ restic_non_root_setup_user }}"
  when: restic_non_root_setup | bool

- name: Test the binary
  ansible.builtin.shell: "{{ restic_bin_bath }} version | grep restic"
  ignore_errors: true
  register: restic_test_result
  changed_when: true

- name: Remove faulty binary
  ansible.builtin.file:
    path: '{{ restic_bin_bath }}'
    state: absent
  when: restic_test_result.rc != 0

- name: Fail if restic could not be installed
  ansible.builtin.fail:
    msg: >-
      Restic binary has been faulty and has been removed.
      Try to re-run the role and make sure you have bzip2 installed!
  when: restic_test_result.rc != 0

- name: Create symbolic link to the correct version
  ansible.builtin.file:
    src: '{{ restic_download_path }}/bin/restic-{{ restic_version }}'
    path: '{{ restic_install_path }}/restic'
    state: link
    force: true
  when: not restic_non_root_setup | bool

- name: Create symbolic link to the correct version (non-root setup)
  ansible.builtin.file:
    src: '{{ restic_download_path }}/bin/restic-{{ restic_version }}'
    path: '{{ restic_install_path }}/restic'
    state: link
    mode: '0750'
  become_user: "{{ restic_non_root_setup_user }}"  # THIS NEEDS apt install acl
  when: restic_non_root_setup | bool

# If this module fails, replace it with command: setcap cap_dac_read_search=+ep
- name: Set capability on the restic app to read-only on the whole system
  community.general.capabilities:
    path: "{{ restic_download_path }}/bin/restic-{{ restic_version }}"
    capability: cap_dac_read_search=+ep
    state: present
  when: restic_non_root_setup | bool
