---
- name: Reformat dict if necessary
  ansible.builtin.set_fact:
    restic_backups: '{{ restic_backups | dict2items | json_query("[*].value") }}'
  when:
    - restic_backups | type_debug == "dict"

- name: "Set user and group to be used (non-root setup)"
  ansible.builtin.set_fact:
    _restic_user: '{{ restic_non_root_setup_user }}'
    _restic_group: '{{ restic_dir_group }}'
  when: restic_non_root_setup | bool

- name: "Set user and group to be used"
  ansible.builtin.set_fact:
    _restic_user: '{{ restic_dir_owner }}'
    _restic_group: '{{ restic_dir_group }}'
  when: not restic_non_root_setup | bool

- name: Create backup credentials
  ansible.builtin.template:
    src: '{{ restic_access_template }}'
    dest: '{{ restic_script_dir }}/access-{{ item.name }}.sh'
    mode: '0400'
    owner: '{{ _restic_user }}'
    group: '{{ _restic_group }}'
    #  no_log: true
  with_items: '{{ restic_backups }}'
  when:
    - item.name is defined
    - item.src is defined or item.stdin is defined
    - item.src is defined or item.stdin and item.stdin_cmd is defined
    - item.repo in restic_repos

- name: Create backup script
  ansible.builtin.template:
    src: '{{ restic_backup_template }}'
    dest: '{{ restic_script_dir }}/backup-{{ item.name }}.sh'
    mode: '0500'
    owner: '{{ _restic_user }}'
    group: '{{ _restic_group }}'
  with_items: '{{ restic_backups }}'
  when:
    - item.name is defined
    - item.src is defined or item.stdin is defined
    - item.src is defined or item.stdin and item.stdin_cmd is defined
    - item.repo in restic_repos

- name: Create forget script
  ansible.builtin.template:
    src: '{{ restic_forget_template }}'
    dest: '{{ restic_script_dir }}/forget-{{ item.name }}.sh'
    mode: '0700'
    owner: '{{ _restic_user }}'
    group: '{{ _restic_group }}'
  with_items: '{{ restic_backups }}'
  when:
    - item.name is defined
    - item.src is defined or item.stdin is defined
    - item.src is defined or item.stdin and item.stdin_cmd is defined
    - item.repo in restic_repos

- name: Setup systemd
  block:
    - name: "Add unit failure script for restic"
      ansible.builtin.template:
        src: "{{ restic_failure_template }}"
        dest: "{{ restic_failure_script }}"
        mode: "0700"
        owner: root
        group: root
    - name: "Add systemd failure for restic"
      ansible.builtin.template:
        src: "{{ restic_systemd_failure_service_template }}"
        dest: "/etc/systemd/system/{{ restic_systemd_failure_service_name }}"
        mode: "0644"
        owner: root
        group: root
      notify:
        - Reload systemd
      tags:
        - molecule-idempotence-notest
    - name: Create systemd units per backup
      ansible.builtin.include_tasks: 'systemd.yml'
      with_items: '{{ restic_backups }}'
