---
- name: "Fail when timer item.name not defined"
  fail:
    msg: "you must define name for {{ item }}"
  when: item.name is not defined

- name: "Add systemd service {{ item.name }}"
  template:
    src: "{{ restic_systemd_service_template }}"
    dest: "/etc/systemd/system/restic-{{ item.name }}.service"
    mode: "0644"
    owner: root
    group: root
  notify:
    - Reload systemd

- name: "Add systemd {{ item.name }} timer"
  template:
    src: "{{ restic_systemd_timer_template }}"
    dest: "/etc/systemd/system/restic-{{ item.name }}.timer"
    mode: "0644"
    owner: root
    group: root
  notify:
    - Reload systemd
  when:
    - restic_create_systemd_timer
    - item.schedules | default([]) | length > 0

- name: "Enable systemd {{ item.name }} timer"
  ansible.builtin.systemd:
    name: "restic-{{ item.name }}.timer"
    enabled: true
    state: "restarted"
  when:
    - restic_create_systemd_timer
    - item.schedules | default([]) | length > 0
