---
- name: "include tasks for testing backup files"
  include_tasks: "test_backup_files.yml"
  with_items:
    - file: backup-dicttest.sh
      location: ~/restic/scripts
    - file: backup-test.sh
      location: ~/restic/scripts
    - file: backup-test_stdin.sh
      location: ~/restic/scripts
    - file: backup-opt_stuff.sh
      location: /home/restic/workDir/scripts

- name: "include tasks for testing access files"
  include_tasks: "test_access_files.yml"
  with_items:
    - file: access-dicttest.sh
      location: ~/restic/scripts
    - file: access-test.sh
      location: ~/restic/scripts
    - file: access-test_stdin.sh
      location: ~/restic/scripts
    - file: access-opt_stuff.sh
      location: /home/restic/workDir/scripts
