---
- name: "Stat test access file {{ item }}"
  stat:
    path: ~/restic/scripts/{{ item }}
  register: test_file

- name: "Check that the test access file {{ item }} exists"
  assert:
    that:
      - test_file.stat.exists
