---
- name: "Stat test backup file {{ item }}"
  stat:
    path: ~/restic/scripts/{{ item }}
  register: test_file

- name: "Check that the test backup {{ item }}  file exists"
  assert:
    that:
      - test_file.stat.exists

- name: "Run the backup scripts {{ item }}"
  shell: "./{{ item }}"
  args:
    chdir: ~/restic/scripts
