---
- name: "Stat test access file {{ item.file }}"
  stat:
    path: "{{ item.location }}/{{ item.file }}"
  register: test_file

- name: "Check that the test access file {{ item.file }} exists"
  assert:
    that:
      - test_file.stat.exists
