---
- name: "Stat test backup file {{ item.file }}"
  stat:
    path: "{{ item.location }}/{{ item.file }}"
  register: test_file

- name: "Check that the test backup {{ item.file }}  file exists"
  assert:
    that:
      - test_file.stat.exists

- name: "Run the backup scripts {{ item.file }}"
  shell: "./{{ item.file }}"
  args:
    chdir: "{{ item.location }}"
