---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu-2004
    image: 'geerlingguy/docker-ubuntu2004-ansible:latest'
    privileged: true
    pre_build_image: true
  - name: ubuntu-2204
    image: 'geerlingguy/docker-ubuntu2204-ansible:latest'
    privileged: true
  - name: debian-11
    image: 'geerlingguy/docker-debian11-ansible:latest'
    privileged: true
    pre_build_image: true
lint: |
  set -ex
  yamllint .
  ansible-lint .
provisioner:
  name: ansible
  inventory:
    host_vars:
      ubuntu-2004:
        restic_skip_checksum_verify: false
  playbooks:
    converge: playbook.yml
scenario:
  name: default
verifier:
  name: ansible
